# Docker Compose configuration for ElderlyCare microservices

services:
  eureka-server:
    build: ./eureka-server
    image: montahajaballah/eureka-server:latest 
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net
  medication-service:
    build: ./MedicationService
    image: montahajaballah/medication-service:latest 
    container_name: medication-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    depends_on:
      - eureka-server
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge