package tn.elderlycare.medicationservice.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import tn.elderlycare.medicationservice.entity.Reminder;

@Service
public class EmailService {

    private final JavaMailSender emailSender;

    @Value("${app.email.receiver}")
    private String emailReceiver;

    public EmailService(JavaMailSender emailSender) {
        this.emailSender = emailSender;
    }

    public void sendOverdueReminderEmail(Reminder reminder) throws MessagingException {
        MimeMessage message = emailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message, true);

        helper.setTo(emailReceiver);
        helper.setSubject("⚠️ Overdue Medication Reminder: " + reminder.getMedication().getName());

        String htmlContent = String.format(
                "<html><body>" +
                        "<h2>Overdue Medication Reminder</h2>" +
                        "<p>You missed a dose of <strong>%s</strong> for Patient ID: <strong>%d</strong>.</p>" +
                        "<p><strong>Dosage:</strong> %s</p>" +
                        "<p><strong>Scheduled Time:</strong> %s</p>" +
                        "<p>Please take the medication as soon as possible or consult your healthcare provider.</p>" +
                        "<br><small>This notification is generated by ElderlyCare Medication Service.</small>" +
                        "</body></html>",
                reminder.getMedication().getName(),
                reminder.getMedication().getPatientId(),
                reminder.getMedication().getDosage(),
                reminder.getReminderTime().toString()
        );

        helper.setText(htmlContent, true);
        emailSender.send(message);
    }
}