package com.elderlycare.medicalequipment.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;

@Service
public class EmailService {

    private final JavaMailSender emailSender;
    
    @Value("${app.email.receiver}")
    private String emailReceiver;

    public EmailService(JavaMailSender emailSender) {
        this.emailSender = emailSender;
    }

    public void sendRiskAlertEmail(String equipmentName, String status) throws MessagingException {
        MimeMessage message = emailSender.createMimeMessage();
        MimeMessageHelper helper = new MimeMessageHelper(message, true);

        helper.setTo(emailReceiver);
        helper.setSubject("⚠️ Weather Risk Alert: " + equipmentName);

        String htmlContent = String.format(
            "<html><body>" +
            "<h2>Risk Alert for Equipment: %s</h2>" +
            "<p><strong>Status:</strong> %s</p>" +
            "<p>Please take necessary precautions.</p>" +
            "<br><small>This alert is generated by ElderlyCareHub.</small>" +
            "</body></html>",
            equipmentName, status
        );

        helper.setText(htmlContent, true);
        emailSender.send(message);
    }
}
